export const SPA_ENTITIES = {
  climate: 'climate.spa_thermostat',
  status: 'select.spa_heater_mode',
  currentTemp: 'sensor.spa_current_temperature',
  targetTemp: 'number.spa_target_desired_temperature',
  heaterState: 'sensor.spa_heater',
  filterCycle1: 'sensor.spa_filter_1',
  filterCycle2: 'sensor.spa_filter_2',
  waterQualityPh: 'sensor.hot_tub_ph',
  waterQualityOrp: 'sensor.hot_tub_oxydo_reduction_potential',
  icoTemp: 'sensor.hot_tub_temperature',
  icoBattery: 'sensor.hot_tub_battery',
  icoRecommendation: 'sensor.spa_ico_recommendation',
  phMinimum: 'input_number.spa_ph_minimum',
  phMaximum: 'input_number.spa_ph_maximum',
  phWatchMinimum: 'input_number.spa_ph_watch_minimum',
  phWatchMaximum: 'input_number.spa_ph_watch_maximum',
  orpMinimum: 'input_number.spa_orp_minimum',
  orpMaximum: 'input_number.spa_orp_maximum',
  orpWatchMinimum: 'input_number.spa_orp_watch_minimum',
  orpWatchMaximum: 'input_number.spa_orp_watch_maximum',
  jets1: 'switch.spa_pump_1',
  jets2: 'switch.spa_pump_2',
  blower: 'switch.spa_blower',
  lights: 'switch.spa_light',
  standbyTemp: 'input_number.spa_standby_temperature',
  sonos: 'media_player.spa_sonos_port',
  outdoorGamesRoom: 'switch.iport_area_4',
  outdoorGazebo: null,
  alert: 'sensor.spa_total_alerts',
  fault: 'sensor.spa_fault_message',
  online: 'binary_sensor.isonline',
};

export const SPA_TARGET_PRESETS = {
  ready: 38,
};

export const SPA_HISTORY_ENTITIES = {
  balboaTemperature: 'sensor.spa_current_temperature',
  icoTemperature: 'sensor.hot_tub_temperature',
  targetTemperature: 'number.spa_target_desired_temperature',
  ph: 'sensor.hot_tub_ph',
  orp: 'sensor.hot_tub_oxydo_reduction_potential',
};
